# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacekitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'WITFaceKit'

  # Pods for FacekitDemo

  target 'FacekitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacekitDemoUITests' do
    # Pods for testing
  end

end
